name: gifty_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1
  provider: ^6.1.5+1
  realm: ^20.0.0
  path_provider: ^2.1.5
  path: ^1.9.1
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  realm_generator: ^20.0.0
  build_runner: ^2.4.13

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/backButton.svg
    - assets/images/bigBox.svg
    - assets/images/check.svg
    - assets/images/chore.svg
    - assets/images/homeImage.svg
    - assets/images/plusImage.svg
    - assets/images/qwerimage.svg
    - assets/images/searchImage.svg
    - assets/images/share.svg
    - assets/images/trash.svg
    - assets/images/set.svg
    - assets/images/tag.svg
    - assets/images/house.svg
    - assets/images/calender.svg
    - assets/images/arrowDown.svg
  fonts:
    - family: OngeulipParkDahyeon
      fonts:
        - asset: assets/fonts/온글잎 박다현체.ttf
    - family: OngeulipConcon
      fonts:
        - asset: assets/fonts/온글잎 콘콘체.ttf
    - family: GumiRomance
      fonts:
        - asset: assets/fonts/Gumi Romance.ttf
    - family: MemomentKkukkkuk
      fonts:
        - asset: assets/fonts/memomentKkukkkuk.ttf

